### ISSUE TITLE
work more carefully and pay attention to details!

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#1]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Quiz.cs#L20
What is this line doing here? 
In case you missed it, Visual studio even marks this for you to pay attention

Also, here you are still using Count() 
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Quiz.cs#L16

Both issues I already mentioned 👆

**Comment by GodWasaProgrammer** [comment]
corrected with commit : 551d93da24a47da94c5df95956f8875d1abe7302
