### ISSUE TITLE
Why create an empty list and then populate it?

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#2]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Program.cs#L9-L12
When you instead could just create a List on the return value?

.. oh I see, because your 
```public static List<Quiz> ReadFromXML(List<Quiz> quizList)``` method is wrong 👆 
Why does this method take a list as param when it just overrides it anyway?

**Comment by GodWasaProgrammer** [comment]
Corrected with commit : aad0ff1eafd8cc618ddce7c426061a07eefaf5ab
