### ISSUE TITLE
Think about if you really need to store your quizList on program exit

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#3]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Program.cs#L155

The only situation when the user has edited your quizlist is after adding new questions

**Comment by GodWasaProgrammer** [comment]
Corrected with commit : d525ce324c617acdae868df36168a53557a8b575
