### ISSUE TITLE
Env.Exit is bad practice for cases with no explizit error code

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#4]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Program.cs#L157

I also wrote in my last feedback
"This is okay in your program, but usually bad practice, most of the time you can just quit your program from Main using a "return". "
Which means "there is no error if you start your program but it is not good code so please change it"

**Comment by GodWasaProgrammer** [comment]
corrected with commit : f3cb21250aaefb42802b4c6121cf6752decdca49
