### ISSUE TITLE
This method is still not working properly

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#5]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/GameLogic.cs#L30-L61
If there would be multiple correct answers and the user just enters all the possible answers and the last one would be a correct one, 
the value of wasTheAnswerCorrect  would be just set to true, completely ignoring what the previous value was.

Additionally this line ```int answerByIndex = answer; ``` does not make sense, right?

**Comment by GodWasaProgrammer** [comment]
fixed with 9a2bb93b1b926533a677f3a8cf90f68b607d8b41 , forgot to mention issue in commit.
