### ISSUE TITLE
Don't use a public static variable for internal states

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#6]
Why having a public static variable that can be seen and changed from every place in your code at all?
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/GameLogic.cs#L9

This method is ok 👌 Because you can call from the outside to increase the internal state
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/GameLogic.cs#L63-L66

but here you again just access the variable representing internal state:
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Program.cs#L141

I already pointed all this out and even made suggestions:
> You have a static ! variable in your gameLogic (which means it is accessible everywhere in your code) that you modify from outside 
  by adding a value of the same class. Instead you should either let the gameLogic completely by itself handle the tracking of points
  by providing a Method like "IncreasePoints()" that adds the internal constant to the value itself and either return the new points
  or provide a method that returns the current amount of points

**Comment by GodWasaProgrammer** [comment]
corrected, i did however forget to put it in commit message, unclear which one it was, but there now exists a GetScore method which works just like a prop

**Comment by incredibleLeitman** [comment]
But "currentScore " is still defined public :p
