### ISSUE TITLE
Use underscore for constants

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#7]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Constants.cs#L11-L18
I don't know how often I have already mentioned this, please pay attention 👆 
Constants should be separated with _ because otherwise they are very unreadable, especially if the names get longer.

Also naming is kinda off:

MAXIMUMACCEPTABLEANSWERCHOICE , how ist this different from MAXANSWERS?
and this comment "// max accepted answers is 5" does not help at all... It can be seen that the value is set to 5 but if the name is not explanatory enough, write a comment that tells the reader what this is for

NUMBEROFQUESTIONSTOBEASKED again, how is this different from MAXANSWERS?
and a "To be asked" suffix is usually redundant.

Think about if you really need a redundant MINGUESSASSTRING when you could just use MINGUESSVALUE.ToString() instead?

also be consistent, you currently are mixing 
 MAX and MAXIMUM

**Comment by GodWasaProgrammer** [comment]
corrected with commit : 96dc3118f784d91f6e702a31a5918562305ca52e
