### ISSUE TITLE
Remove unnecessary usings

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#8]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/bf48f9b44d5d797ff45ab02da9e6d90e7c7ca2f4/Constants.cs#L1-L5
Do you really need System.Linq for example here?

Check this for all files, every time before you commit your changes

**Comment by GodWasaProgrammer** [comment]
corrected with commit : f1b37e2e44ef2f0dfefb250f831cc8120780677d
