### ISSUE TITLE
Why is this a separate method?

### ISSUE THREAD

**Issue by incredibleLeitman** [GodWasaProgrammer/QuizMaker-RM#9]
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/aad0ff1eafd8cc618ddce7c426061a07eefaf5ab/UI.cs#L215
https://github.com/GodWasaProgrammer/QuizMaker-RM/blob/aad0ff1eafd8cc618ddce7c426061a07eefaf5ab/UI.cs#L229-L232

You only call it once from an UI method that reads a string, 
so you could just Console.WriteLine in there and done

**Comment by GodWasaProgrammer** [comment]
corrected with commit : f1b37e2e44ef2f0dfefb250f831cc8120780677d
